[tool.poetry]
name = "pyproject"
version = "0.1.0"
description = ""
authors = ["JoMingyu"]
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.82.0"
SQLAlchemy = "^1.4.40"
mysqlclient = "^2.1.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
autoflake = "^1.5.2"
isort = "^5.10.1"
pre-commit = "^2.20.0"
pytest = "^7.1.2"
mypy = "^0.971"
pytest-cov = "^3.0.0"
flake8 = "^5.0.4"
pylint = "^2.15.0"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = "tests"
filterwarnings = "error"
addopts = '''
  --strict-markers
  --tb=short
  --cov=app
  --cov=tests
  --cov-branch
  --cov-report=term-missing
  --cov-report=html
  --cov-report=xml
  --no-cov-on-fail
  --cov-fail-under=100
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
